version: '3.8'
services: 
  node-app2:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
  mysql-db:
    image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: testdb
      ports:
        - "3306:3306"
